# Generated by Django 2.0.6 on 2018-08-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_todo_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='subtask',
            field=models.TextField(default=''),
        ),
    ]
