# Generated by Django 2.0.6 on 2018-08-14 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_todo_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2018, 8, 14, 5, 40, 36, 49706)),
        ),
    ]
